services:
  textclf-api:
    build: .
    image: textclf-api:monitor
    container_name: textclf-api
    environment:
      - MODEL_POINTER=stable   # change to latest if you want
      - LOG_LEVEL=INFO
      - RATE_LIMIT_ENABLED=1
      - RATE_LIMIT_PREDICT=100/second
      - SHOW_DOCS=1
      # - SLOWAPI_STORAGE_URI=redis://redis:6379/0
    volumes:
      - ./artifacts:/app/artifacts
    ports:
      - "8000:8000"
    command: >
      uvicorn textclf.api:app --host 0.0.0.0 --port 8000

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # alerts file is optional; mount only if you have it already
      # - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --web.listen-address=:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  prometheus_data: