[mypy]
python_version = 3.10
ignore_missing_imports = True
namespace_packages = True
explicit_package_bases = True
mypy_path = src

# extra safety: ignore noisy third-party packages explicitly
[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-joblib.*]
ignore_missing_imports = True